version: "3.9"

services:
  contoso-backend:
    container_name: contoso-backend
    build:
      context: .
      dockerfile: Dockerfile.java
    ports:
      - "8080:8080"
    environment:
      - CODESPACE_NAME
      - GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN
    networks:
      - contoso

  contoso-frontend:
    container_name: contoso-frontend
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    ports:
      - "3030:8080"
    environment:
      - ApiSettings__BaseUrl=http://contoso-backend:8080/api
    networks:
      - contoso

networks:
  contoso:
    name: contoso
